<?php

function nfa_escape($value): string {
    return htmlspecialchars((string)($value ?? ''), ENT_QUOTES, 'UTF-8');
}

function nfa_file_exists_rel(string $relPath): bool {
    $relPath = ltrim(str_replace(['\\', '//'], '/', $relPath), '/');
    $abs = dirname(__DIR__) . '/' . $relPath;
    return is_file($abs);
}

function nfa_branch_context(PDO $pdo, int $branch_id): ?array {
    if ($branch_id <= 0) return null;

    $stmt = $pdo->prepare(
        "SELECT b.branch_id, b.branch_name, b.address, b.contact_number, b.website_link, r.region_name\n" .
        "FROM branch b\n" .
        "JOIN regions r ON r.region_id = b.region_id\n" .
        "WHERE b.branch_id = ?\n" .
        "LIMIT 1"
    );
    $stmt->execute([$branch_id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row ?: null;
}

function nfa_optional_logo_img(string $src, string $alt, string $class = 'hdr-logo'): string {
    if (!nfa_file_exists_rel($src)) return '';
    return '<img class="' . nfa_escape($class) . '" src="' . nfa_escape($src) . '" alt="' . nfa_escape($alt) . '">';
}

function nfa_first_existing_logo(array $candidates, string $alt, string $class = 'hdr-logo'): string {
    foreach ($candidates as $src) {
        $img = nfa_optional_logo_img((string)$src, $alt, $class);
        if ($img !== '') return $img;
    }
    return '';
}

function nfa_print_header(string $title, ?array $branchCtx = null, array $opts = []): void {
    $subtitle = (string)($opts['subtitle'] ?? 'National Food Authority');
    $hideDocTitle = (bool)($opts['hide_doc_title'] ?? false);

    $branchLine = '';
    if ($branchCtx) {
        $branchName = trim((string)($branchCtx['branch_name'] ?? ''));
        $regionName = trim((string)($branchCtx['region_name'] ?? ''));
        $address = trim((string)($branchCtx['address'] ?? ''));

        $parts = [];
        if ($branchName !== '') $parts[] = $branchName;
        if ($regionName !== '') $parts[] = $regionName;
        $branchLine = implode(' • ', array_map('nfa_escape', $parts));

        if ($address !== '') {
            $branchLine .= ($branchLine !== '' ? '<br>' : '') . nfa_escape($address);
        }
    }

    $leftLogos =
        nfa_first_existing_logo(['img/da-logo.png', 'img/da-logo.jpg', 'img/da-logo.jpeg'], 'DA Logo') .
        nfa_first_existing_logo(['img/nfa-logo.png', 'img/nfa-logo.jpg', 'img/nfa-logo.jpeg'], 'NFA Logo');

    if (trim($leftLogos) === '') {
        $leftLogos = '<img class="hdr-logo" src="img/nfa-logo.png" alt="NFA Logo">';
    }

    // User-provided BP logo can be bp-logo.jpg/jpeg.
    $rightLogo = nfa_first_existing_logo(
        ['img/bp-logo.jpeg', 'img/bp-logo.jpg', 'img/bagong-pilipinas.png', 'img/bagong-pilipinas.jpg', 'img/bagong-pilipinas.jpeg'],
        'Bagong Pilipinas'
    );

    echo '<div class="print-header">';
    echo '  <div class="hdr-row">';
    echo '    <div class="hdr-logos-left">' . $leftLogos . '</div>';
    echo '    <div class="hdr-center">';
    echo '      <p class="hdr-title">' . nfa_escape($subtitle) . '</p>';
    if (!$hideDocTitle && trim($title) !== '') {
        echo '      <p class="hdr-subtitle">' . nfa_escape($title) . '</p>';
    }
    echo '      <div class="hdr-meta">';
    if ($branchLine !== '') {
        echo '        <div>' . $branchLine . '</div>';
    }
    echo '      </div>';
    echo '    </div>';
    echo '    <div class="hdr-logos-right">' . $rightLogo . '</div>';
    echo '  </div>';
    echo '</div>';
}

function nfa_print_footer(?array $branchCtx = null, array $opts = []): void {
    $left = (string)($opts['left'] ?? 'Generated by NFA Appointment System');
    $generated = (string)($opts['generated'] ?? date('Y-m-d H:i'));

    $contactLine = '';
    if ($branchCtx) {
        $contact = trim((string)($branchCtx['contact_number'] ?? ''));
        $website = trim((string)($branchCtx['website_link'] ?? ''));
        $parts = [];
        if ($contact !== '') $parts[] = 'Tel: ' . $contact;
        if ($website !== '') $parts[] = $website;
        $contactLine = implode(' • ', $parts);
    }

    echo '<div class="print-footer">';
    echo '  <div style="display:flex; justify-content:space-between; gap:12px;">';
    echo '    <div>' . nfa_escape($left) . ($contactLine !== '' ? '<br><span class="muted">' . nfa_escape($contactLine) . '</span>' : '') . '</div>';
    echo '    <div class="muted">Generated: ' . nfa_escape($generated) . '</div>';
    echo '  </div>';
    echo '</div>';
}
